Repository chausovSurfStudio/TextFieldsCatalog, pull requests merged in 2019-11, with the labels that each got.

#51 Dev/validation policy
  Docs/Usage.md
  Example/TextFieldsCatalogExample/TextFields/TextFields/CustomUnderlinedTextField/CustomUnderlinedTextField.swift
  TextFieldsCatalog.xcodeproj/project.pbxproj
  TextFieldsCatalog.xcodeproj/xcshareddata/xcschemes/TextFieldsCatalog.xcscheme
  TextFieldsCatalog/Resources/Constants/ValidationPolicy.swift
  TextFieldsCatalog/TextFields/BorderedTextField/BorderedTextField.swift
  TextFieldsCatalog/TextFields/UnderlinedTextField/UnderlinedTextField.swift
  TextFieldsCatalog/TextFields/UnderlinedTextView/UnderlinedTextView.swift
Labels: documentation, feature

#52 Make commonButton internal
  Example/Podfile
  Example/TextFieldsCatalogExample/Library/Reusable/MainButton.swift
  TextFieldsCatalog/Library/BaseClasses/CommonButton.swift
  TextFieldsCatalog/Library/Reusable/IconButton.swift
Labels: update

#53 Add default textfield placeholder
  Docs/Usage.md
  TextFieldsCatalog/TextFields/UnderlinedTextField/UnderlinedTextField.swift
  TextFieldsCatalog/TextFields/UnderlinedTextView/UnderlinedTextView.swift
Labels: feature

#55 Update to 0.6.0
  Docs/Usage.md
  Example/Podfile
  Example/TextFieldsCatalogExample/Library/Reusable/MainButton.swift
  Example/TextFieldsCatalogExample/TextFields/TextFields/CustomUnderlinedTextField/CustomUnderlinedTextField.swift
  TextFieldsCatalog.podspec
  TextFieldsCatalog.xcodeproj/project.pbxproj
  TextFieldsCatalog.xcodeproj/xcshareddata/xcschemes/TextFieldsCatalog.xcscheme
  TextFieldsCatalog/Library/BaseClasses/CommonButton.swift
  TextFieldsCatalog/Library/Reusable/IconButton.swift
  TextFieldsCatalog/Library/Utils/MaskTextFieldFormatter.swift
  TextFieldsCatalog/Resources/Constants/ValidationPolicy.swift
  TextFieldsCatalog/TextFields/BorderedTextField/BorderedTextField.swift
  TextFieldsCatalog/TextFields/UnderlinedTextField/UnderlinedTextField.swift
  TextFieldsCatalog/TextFields/UnderlinedTextView/UnderlinedTextView.swift
Labels: documentation, feature

#56 fixed default parameter for isNativePlaceholder flag
  TextFieldsCatalog/TextFields/UnderlinedTextField/UnderlinedTextField.swift
Labels: bug
